# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-27 00:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.jpeg', upload_to='image')),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.IntegerField(blank=True, default=0)),
                ('levels', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
