# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 01:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escapeRoom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.CharField(blank=True, max_length=430),
        ),
        migrations.AddField(
            model_name='userdata',
            name='players',
            field=models.ManyToManyField(related_name='players', to=settings.AUTH_USER_MODEL),
        ),
    ]
