# Generated by Django 2.0.4 on 2018-04-09 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escapeRoom', '0002_auto_20180328_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('content', models.ImageField(upload_to='')),
                ('status', models.IntegerField(blank=True, default=0)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('point_x', models.FloatField(blank=True, default=0.0)),
                ('point_y', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_id', models.IntegerField()),
                ('background', models.TextField()),
                ('status', models.IntegerField(blank=True, default=0)),
                ('items', models.ManyToManyField(default=None, related_name='items', to='escapeRoom.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_x', models.FloatField(blank=True, default=0.0)),
                ('point_y', models.FloatField(blank=True, default=0.0)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='players',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='status',
        ),
        migrations.AddField(
            model_name='mission',
            name='players',
            field=models.ManyToManyField(default=None, related_name='players', to='escapeRoom.Player'),
        ),
        migrations.AddField(
            model_name='item',
            name='player',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='escapeRoom.Player'),
        ),
        migrations.AddField(
            model_name='item',
            name='relations_p',
            field=models.ManyToManyField(blank=True, default=None, related_name='_item_relations_p_+', to='escapeRoom.Item'),
        ),
    ]
