# Generated by Django 2.0.4 on 2018-04-10 00:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('escapeRoom', '0003_auto_20180409_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='players',
            field=models.ManyToManyField(related_name='palyed_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
