# Generated by Django 2.0.4 on 2018-04-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeRoom', '0005_auto_20180420_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='background',
        ),
        migrations.AddField(
            model_name='mission',
            name='game_id',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
