# Generated by Django 2.0.4 on 2018-04-29 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapeRoom', '0009_auto_20180429_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='player',
        ),
        migrations.RemoveField(
            model_name='item',
            name='relations_p',
        ),
    ]
