# Generated by Django 2.0.4 on 2018-04-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escapeRoom', '0010_auto_20180429_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomstart', models.IntegerField(default=10000)),
            ],
        ),
    ]
