# Generated by Django 2.0.4 on 2018-04-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escapeRoom', '0011_single'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Single',
        ),
    ]
